---
title: "R-S2dio"
subtitle: "STA 199 Project"
format: html
editor: visual
---

Significant knowledge gaps exist in the main components that create a seeding assignment for Division 1 college basketball teams that make it to the National Collegiate Athletics Association (NCAA), also known as 'March Madness'. The 64 teams that qualify for the D-1 national championship are assigned to be a 1-16 seed, in which 1 is the best seed ranking; there are 4 teams for each numerical ranking, meaning that there are 4 D-1 college basketball programs deemed a 1 seed, 4 deemed a 2 seed, and so on. Our group centered our research around the question, "How does regular season adjusted offensive efficiency and regular season adjusted defensive efficiency predict postseason seed?". In the end, we found that in the regular season, teams with higher adjusted offensive efficiency & lower adjusted defensive efficiency will be predicted to have better seed assignments. This project utilized scatter plot visualizations, as well as additive and interactive models to justify our findings.
