---
title: "Project title"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

**Dataset 2 (D1 college basketball)**

**Introduction and data**

As Duke students, it goes without saying that Duke basketball adds on to our unique college experience. Noting Duke mens basketball's historical successes, we have grown interested in researching more about other Division 1 mens basketball programs in universities throughout the country.

The data that we will be utilizing is sourced from the Division I college basketball seasons from the years of 2013-2019. It was found in the open source data site, Kaggle. The data was scraped from http://barttorvik.com/trank.php#. This data was cleaned up in 2021, in which the COVID seasons were not included in the dataset.

The dataset has various variables that characterize different Division I basketball teams--- such as the university they represent and the conference in which they belong. Some of the observations within the dataset include the number of games played, the number of games won, power rating, as well as the stats of the team in a particular season.

**Methodology**

**Our research question: "Which Division 1 basketball conference has the highest overall success rate from the 2013-2019 seasons? And which best factors (other than wins)--- (offensive/ defensive efficiency, 2pt and 3pt field goal success, steal rate, turnover rate, etc)--- best predict overall regular season success from 2013 to 2019? And does this also predict (better predict/ worse predict) post season success?"**

*\*We define "overall success rate" through the metrics of number of game wins, offensive rebound rates, total points, etc.*

Our central research question (the first question) is addressed through the analysis of the factors that best predict overall regular season success from 2013 to 2019. We might be able to filter out the different factors that play a role in each program's success and determine their 'weight' in assigning regular season rankings. This processes is then applied to investigate if such factor better predicts post season success/ pre-season rankings for the next basketball season.

We predict that the conference with the most programs ranked highly will be considered the D1 mens basketball conference with the highest overall success rate. We also predict that an individual program will be ranked higher by the number of points they scored, in relation to their opponent, regardless of the outcome.

**Results**

-- What are you finding out?

-- Make sure that this is connected to your research question. It is easy to get excited and explore your data set. Make sure that all results you generate are in-line with the research question you have asked

**W+F**
